version: "3.9"

services:
  nodejs:
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: always
    ports:
      - ${WEBSOCKET_PORT}:${WEBSOCKET_PORT}
    networks:
      - chain-reaction
    command: npx ts-node src/Server/WebSocketServer.ts

networks:
  chain-reaction:
    driver: bridge
